### ISSUE TITLE
Bug: AssertionError when --cutoff-analysis was set

### ISSUE THREAD

**Issue by freedog8** [taoliu/MACS#341] opened 2019-11-02 03:01 UTC
**Describe the bug**
An exception was thrown when run callpeak program with --cutoff-analysis set.

**Screenshots**
![image](https://user-images.githubusercontent.com/21093659/68064733-40f20e80-fd5a-11e9-85c8-ee70b869f1a9.png)
**Screenshots (no --cutoff-analysis)**
![image](https://user-images.githubusercontent.com/21093659/68064798-2ec4a000-fd5b-11e9-97ae-4c4808c5b92f.png)

**Screenshots (with control, maybe another issue) **
![image](https://user-images.githubusercontent.com/21093659/68065148-af859b00-fd5f-11e9-83db-2d3e84ee3924.png)
![image](https://user-images.githubusercontent.com/21093659/68065151-b6aca900-fd5f-11e9-8789-d783602c66ed.png)

**Another data with contorl**
![image](https://user-images.githubusercontent.com/21093659/68065024-4b160c00-fd5e-11e9-93a3-2a33e265f5e7.png)
![image](https://user-images.githubusercontent.com/21093659/68065033-59fcbe80-fd5e-11e9-9a3f-09ff0738aaf4.png)

**Another data with contorl  (no --cutoff-analysis)**
![image](https://user-images.githubusercontent.com/21093659/68065058-89abc680-fd5e-11e9-99e6-82d1ffb5f71a.png)
![image](https://user-images.githubusercontent.com/21093659/68065069-acd67600-fd5e-11e9-9e97-c77e08c1b73e.png)

**System (please complete the following information):**
 - OS: Linux
 - python-3.7.5
 - numpy-1.17.2
 - macs2 2.2.5

**Comment by taoliu** [comment] 2019-11-02 05:13
Hi @freedog8. In the first three cases, the fragment size inferred from BAMPE file is 0 and very few reads are "valid" after filtering. It seems that MACS2 can't correctly read the information. Could you share with me a chunk of your clean.bam file from bowtie? A way to get around this is to convert the BAMPE into a BEDPE file. In the BEDPE file, you just need three columns: chromosome, the leftmost position of the read pair, and the rightmost position of the read pair.

As for the "Another data with control", the complaint on rcond is caused by numpy. I will update the code to silence the warning. And the ValueError can be a quick fix. Stay tuned.

**Comment by taoliu** [comment] 2019-11-02 05:30
hmm... I didn't realize that the find_optimal_cutoff function is an unfinished function from years ago... I have disabled that. The cutoff analysis should output a cutoff analysis table for you, but the 'suggest an optimal cutoff' feature should not be enabled. 

The updates can be found in PR: #342 , and will be included in the next release.

**Comment by freedog8** [comment] 2019-11-02 07:10
> Hi @freedog8. In the first three cases, the fragment size inferred from BAMPE file is 0 and very few reads are "valid" after filtering. It seems that MACS2 can't correctly read the information. Could you share with me a chunk of your clean.bam file from bowtie? A way to get around this is to convert the BAMPE into a BEDPE file. In the BEDPE file, you just need three columns: chromosome, the leftmost position of the read pair, and the rightmost position of the read pair.
> 
> As for the "Another data with control", the complaint on rcond is caused by numpy. I will update the code to silence the warning. And the ValueError can be a quick fix. Stay tuned.

Oh, I just realize that the ChIP-Seq data of the first three cases is single-end. That‘s the reason. Thanks!

**Comment by taoliu** [comment] 2019-11-09 01:43
Cutoff-analysis in callpeak cmd has been fixed in 2dd2839

**Closed by taoliu** 2019-11-09 01:43 UTC
Labels: Bug Report
